// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMo7XlVynIuOX7ft3bB-blt8E0cBoAE3c',
    appId: '1:809064037992:web:883a45cb5380c72c4985dd',
    messagingSenderId: '809064037992',
    projectId: 'mytaskmanager-24899',
    authDomain: 'mytaskmanager-24899.firebaseapp.com',
    storageBucket: 'mytaskmanager-24899.firebasestorage.app',
    measurementId: 'G-HM1FDPPQ1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-nXp50YE2OiYH6vVjk0PJEafouiPtwI',
    appId: '1:809064037992:android:7bc47d7d609fb3d94985dd',
    messagingSenderId: '809064037992',
    projectId: 'mytaskmanager-24899',
    storageBucket: 'mytaskmanager-24899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2raomxXkwI6jsZdamTbd2WKzpLCHMgG8',
    appId: '1:809064037992:ios:c3bd62da91f88c414985dd',
    messagingSenderId: '809064037992',
    projectId: 'mytaskmanager-24899',
    storageBucket: 'mytaskmanager-24899.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2raomxXkwI6jsZdamTbd2WKzpLCHMgG8',
    appId: '1:809064037992:ios:c3bd62da91f88c414985dd',
    messagingSenderId: '809064037992',
    projectId: 'mytaskmanager-24899',
    storageBucket: 'mytaskmanager-24899.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMo7XlVynIuOX7ft3bB-blt8E0cBoAE3c',
    appId: '1:809064037992:web:a9e6ec61edb0ada04985dd',
    messagingSenderId: '809064037992',
    projectId: 'mytaskmanager-24899',
    authDomain: 'mytaskmanager-24899.firebaseapp.com',
    storageBucket: 'mytaskmanager-24899.firebasestorage.app',
    measurementId: 'G-C58ZEJ0EEF',
  );
}
